package main.Modelo.Enums;

public enum Eventos {
    ESPERANDO_JUGADORES,
    NUEVO_JUGADOR,
    NO_SE_PUDO_INGRESAR_JUGADOR_NUEVO,
    APUESTA,
    NO_PUDO_APOSTAR,
    JUGADOR_SE_RETIRO,
    PASAR,
    DESCARTA,
    RECARGA_FICHAS,
    CAMBIO_TURNO,
    GANADOR,

    //FASES DEL JUEGO
    INICIADO,
    APUESTA_INICIAL,
    DESCARTE,
    APUESTA_FINAL,
    JUEGO_TERMINADO
}

